//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OziBazaar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public int ProductPropertyID { get; set; }
        public int ProductID { get; set; }
        public int ProductGroupPropertyID { get; set; }
        public string Value { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductGroupProperty ProductGroupProperty { get; set; }
    }
}
