//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OziBazaar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ProductImageID { get; set; }
        public int ProductID { get; set; }
        public string ImagePath { get; set; }
        public string ImageType { get; set; }
        public string MimeType { get; set; }
        public string Description { get; set; }
        public Nullable<short> ImageOrder { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
