//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OziBazaar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Advertisements = new HashSet<Advertisement>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductProperties = new HashSet<ProductProperty>();
        }
    
        public int ProductID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<Advertisement> Advertisements { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<ProductProperty> ProductProperties { get; set; }
    }
}
