//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OziBazaar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int WishListID { get; set; }
        public int AdvertizementID { get; set; }
        public int UserID { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
    }
}
